import java.util.ArrayList;

/*Generated by Nathan while working on generato
 *Groupsize() present in order to eliminate groupsize field (and required maintenance).
 *One initialization function will likely be eliminated.
 *Modified Monday, Nov 17th.
 *
 *Aditional methods included by Clodomir while working on students needs
 *Tuesday, Nov 18th.
 *
 */

public class Group {
   private ArrayList<Student> groupMembers;
  
    public void addStudent(Student student) {
        this.groupMembers.add(student);
    }
    
    public boolean removeStudent(int studentNumber) {
        Student student =  this.getStudent(studentNumber);
        
        if(student != null){
            this.groupMembers.remove(student);            
            return true;
        }
        else
            return false;
    }    
   
     public ArrayList<Student> getStudents() {
        return this.groupMembers;
    }
    public int groupSize(){
    	return this.groupMembers.size();
    }
     public Student getStudent(int studentNumber) {
        Student student = null;

        if (this.groupMembers.isEmpty()) {
            return null;
        }

        for (int i = 0; i < this.groupMembers.size(); i++) {
            if (this.groupMembers.get(i).getStudentNumber() == studentNumber) {
                student = this.groupMembers.get(i);
            }

        }
        return student;
    }
   
}
